source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'bitcoin_payments', path: '..'

gem 'pry-nav'
gem 'pry-rails'

group :test do
  gem 'minitest-reporters'
end