source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'bitcoin_payments', path: '..'

gem 'pry-nav'
gem 'pry-rails'
group :test do
  gem 'turn', '0.9.6'
  gem 'tconsole', github: 'lihanli/tconsole'
end