source 'https://rubygems.org'

gem 'rails', '4.2.1'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
gem 'bitcoin_active_record', path: '..'

gem 'pry-nav'
gem 'pry-rails'

group(:development) do
  gem 'spring', '1.3.4'
  gem 'spring-commands-testunit'
end

group :test do
  gem 'mocha', '1.1.0'
  gem 'minitest-reporters', '1.0.11'
end
